name: Android CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:
      
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Clone repo
        uses: actions/checkout@v3.1.0

      - name: Setup JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: assembleDebug
          cache-disabled: false
          gradle-home-cache-cleanup: false
    
      - name: Upload apk-debug
        uses: actions/upload-artifact@v3
        if: ${{ !github.head_ref }}
        with:
          name: imje-debug
          path: app/build/outputs/apk/debug/app-debug.apk

